name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para o branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão do Node.js compatível com seu projeto

      # Passo 3: Instalar Dependências
      - name: Install Dependencies
        run: npm install

      # Passo 4: Build do Projeto Astro
      - name: Build Astro
        run: npm run build

      # Passo 5: Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Diretório de saída padrão do Astro
          # Opcional: Especifique o branch e o folder de destino se necessário
          # branch: gh-pages
          # folder: /